<h2>Movie list</h2>

<table id="movie-list" border="1">
    <tr>
        <th>Id</th>
        <th>Title</th>
        <th>Release date</th>
    </tr>
    <?php foreach ($this->movies as $movie): ?>
        <tr>
            <td><?php echo $this->escape($movie->getMovieId()); ?></td>
            <td><?php echo $this->escape($movie->getTitle()); ?></td>
            <td><?php echo $this->escape($movie->getReleaseDate()); ?></td>
        </tr>
    <?php endforeach; ?>
</table>